### USERS ###

GET http://localhost:7500/api/users/ HTTP/1.1
Content-Type: application/json

### ADD USER
POST http://localhost:7500/api/users HTTP/1.1
Content-Type: application/json

{
    "nombres": "Gustavo2",
    "apellidos": "Romero2",
    "documento": "78965452631",
    "telefono": "321456789",
    "email": "gasifero@gmail.com",
    "clave": "123456",
    "rol": "Administrador"
}

### DELETE USER
DELETE http://localhost:7500/api/users/61901c39084ce5ff87b7e063 HTTP/1.1

### LOCATIONS ###

POST http://localhost:7500/api/locations HTTP/1.1
Content-Type: application/json


{
    "departamento": "Risaralda",
    "ciudad": "Pereira",
    "zona": "Este",
    "vereda": "Tribunas",
    "direccion": "Km 6, via armenia, casa 3"
}

### GET ALL LOCATIONS
GET http://localhost:7500/api/locations HTTP/1.1

### GET LOCATION BY ID
GET http://localhost:7500/api/locations/61907f659569dfc8b50001df HTTP/1.1

### UPDATE LOCATION
PUT http://localhost:7500/api/locations/61907f659569dfc8b50001df HTTP/1.1
Content-Type: application/json


{
    "departamento": "Risaralda",
    "ciudad": "Pereira",
    "zona": "Este",
    "vereda": "Tribunas2",
    "direccion": "Km 6, via armenia, casa 3"
}


### DELETE LOCATION
DELETE http://localhost:7500/api/locations/61907f659569dfc8b50001df HTTP/1.1



### PROPERTY ###

### ADD PROPERTY
POST http://localhost:7500/api/properties HTTP/1.1
Content-Type: application/json


{
    "tipo": "casa",
    "ubicacion": "61907f659569dfc8b50001df",
    "area": 380,
    "precio": 850000000,
    "habitaciones": 4,
    "baños": 4,
    "parqueadero": true,
    "descripcion": "Casa campestre",
    "imagenes": ""
}


### GET ALL PROPERTIES
GET http://localhost:7500/api/properties HTTP/1.1

### GET PROPERTIES BY ID
GET http://localhost:7500/api/properties/61914ee3f8ce995637227351 HTTP/1.1

### UPDATE A PROPERTY
PUT http://localhost:7500/api/properties/61914ee3f8ce995637227351 HTTP/1.1
Content-Type: application/json

{
    "tipo": "apartamento",
    "ubicacion": "61907f9f9569dfc8b50001e3",
    "area": 94,
    "precio": 685000000,
    "habitaciones": 2,
    "baños": 2,
    "parqueadero": false,
    "descripcion": "Apartamento amoblado",
    "imagenes": ""
}

### DELETE PROPERTY
DELETE http://localhost:7500/api/properties/61901c39084ce5ff87b7e063 HTTP/1.1